import type { Language } from './LanguageContext'

const pairs: ReadonlyArray<readonly [zh: string, en: string]> = [
  ['首页', 'Home'], ['发现', 'Discover'], ['日历', 'Calendar'], ['校园', 'Campus'], ['体育打卡', 'Sports Check-in'], ['我的活动', 'My Events'], ['通知', 'Notifications'], ['我的校园', 'My Campus'],
  ['主导航', 'Primary navigation'], ['移动端导航', 'Mobile navigation'], ['BNBU Campus Hub 首页', 'BNBU Campus Hub home'], ['个人菜单', 'profile menu'], ['清除搜索', 'Clear search'], ['试试“AI”“running”或“marketing”。', 'Try “AI”, “running”, or “marketing”.'], ['暂时没有校园搜索结果。', 'No campus results yet.'], ['校园主办方', 'Campus host'], ['已准备好', 'ready'],
  ['返回发现', 'Back to Discover'], ['主办方', 'Hosted by'], ['查看主办方', 'View host'], ['关于本活动', 'About this event'], ['活动流程', 'Run of show'], ['你可能遇见的人', 'People you may meet'], ['活动地点', 'Location'], ['相关活动', 'Related Events'],
  ['活动不只是日历中的一个位置；它帮助学生发现社群，并带着一条清晰的新连接离开。', 'More than a place on the calendar, this event is designed to help students discover a community and leave with a clear next connection.'], ['活动当天可查看路线指引', 'Tap directions on the day of the event'],
  ['报名', 'Register'], ['申请参加', 'Request to Join'], ['加入候补', 'Join Waitlist'], ['等待审批', 'Pending Approval'], ['候补第 3 位', 'Waitlist #3'], ['取消报名', 'Cancel Registration'], ['稍后再说', 'Not now'], ['分享', 'Share'], ['联系主办方', 'Contact host'], ['保存', 'Save'], ['已保存', 'Saved'],
  ['确认报名', 'Confirm registration'], ['分享这个校园时刻', 'Share this campus moment'], ['复制活动链接', 'Copy event link'], ['分享到校园社区', 'Share to Campus Community'], ['链接已复制', 'Link copied'],
  ['校园活动，让校园被看见', 'Events make campus visible'], ['发现活动', 'Discover Events'], ['发现正在发生的 BNBU 校园活动', 'Discover what is happening across BNBU'], ['搜索活动、社团、老师或兴趣', 'Search events, organizations, faculty, or interests'], ['全部日期', 'All dates'], ['今天', 'Today'], ['明天', 'Tomorrow'], ['本周', 'This Week'], ['周末', 'Weekend'], ['热门活动', 'Popular This Week'], ['清除筛选', 'Clear filters'], ['没有符合当前条件的活动。', 'No events match this view.'], ['试试其他兴趣或日期。', 'Try another interest or date.'], ['查看活动', 'View Event'],
  ['校园社群', 'Campus Communities'], ['关注那些让校园持续发生的人。', 'Follow the people making things happen.'], ['精选推荐', 'Picked for your interests'], ['为你推荐', 'Recommended for You'], ['查看更多', 'See more'], ['探索', 'Explore'], ['我的社群', 'Your Communities'], ['加入一个组织，让这里开始生长。', 'Join an organization to grow this space.'], ['探索组织', 'Explore organizations'], ['即将开始', 'Upcoming'], ['已确认的对话', 'confirmed conversation'],
  ['明天 · 15:30', 'Tomorrow · 15:30'], ['与张老师对话', 'Chat with Professor Zhang'], ['市场营销 · 职业规划', 'Marketing · Career Planning'], ['你的体育活动可以成为更广阔校园故事的第一条线索。', 'Your sports activity can be the first thread in a wider campus story.'], ['校园旅程', 'Campus Journey'], ['你的一周正在连接起来', 'Your week is connecting'], ['查看个人档案', 'View profile'],
  ['时间', 'When'], ['精选 / BNBU', 'FEATURED / BNBU'], ['构建', 'BUILD'], ['下一步。', "WHAT'S NEXT."], ['周三 · 19:30', 'WEDNESDAY · 19:30'], ['人参加', 'attending'], ['个精选活动', 'CURATED MOMENTS'],
  ['你的校园时间轴', 'Your campus, in time'], ['校园日历', 'Campus Calendar'], ['活动、Coffee Chat 与你主办的校园时刻。', 'Events, Coffee Chats, and moments you host.'], ['月', 'Month'], ['周', 'Week'], ['日程', 'Agenda'], ['上个月', 'Previous month'], ['下个月', 'Next month'], ['你的日程正等待第一个活动。', 'Your agenda is ready for a first event.'],
  ['每一个你答应参加的时刻', 'Everything you said yes to'], ['你的下一段校园经历，以及你正在创造的活动。', 'Your next campus moments and the ones you are creating.'], ['创建活动', 'Create Event'], ['主办中', 'Hosting'], ['往期', 'Past'], ['收藏', 'Saved'], ['你的第一个主办活动从这里开始。', 'Your first hosted event starts here.'], ['Campus Hub 因你选择参与的时刻而生长。', 'Campus Hub grows through the moments you choose.'],
  ['主办一场校园活动', 'Host a campus moment'], ['先从体验本身开始，管理细节可以保持轻量。', 'Start with the experience. Management details can stay light.'], ['封面', 'Cover'], ['为活动建立清晰的视觉识别。', 'Give the event a clear visual identity.'], ['选择模板', 'Choose template'], ['基本信息', 'Basic Information'], ['活动名称', 'Event Name'], ['分类', 'Category'], ['活动介绍', 'Description'], ['时间与地点', 'When & Where'], ['日期', 'Date'], ['开始时间', 'Start Time'], ['结束时间', 'End Time'], ['地点', 'Location'], ['报名设置', 'Registration'], ['开放报名', 'Open Registration'], ['参与者即时加入。', 'Guests join instantly.'], ['需要审批', 'Require Approval'], ['逐一审核申请。', 'Review each request.'], ['人数上限', 'Capacity'], ['候补名单', 'Waitlist'], ['满员后继续保留参与意愿。', 'Keep interest when full.'], ['可见范围', 'Visibility'], ['公开', 'Public'], ['不公开列出', 'Unlisted'], ['仅成员', 'Members Only'], ['准备好就发布', 'Ready when you are'], ['预览活动', 'Preview Event'], ['发布活动', 'Publish Event'], ['活动预览', 'Event Preview'], ['继续编辑', 'Keep editing'], ['活动已发布，嘉宾审核已准备好', 'Event published — guest review is ready'],
  ['活动工作台', 'Live event workspace'], ['查看活动', 'View event'], ['报名人数', 'Registrations'], ['本地 Demo 参与者', 'Local demo guests'], ['已报名', 'Going'], ['已确认', 'Confirmed'], ['待审批', 'Pending'], ['需要审核', 'Needs review'], ['候补', 'Waitlist'], ['可转为已报名', 'Ready to move'], ['已签到', 'Checked In'], ['已到场', 'At the event'], ['参与者名单', 'Guest List'], ['每一个名字都是真实的人。', 'People, not rows.'], ['全部', 'All'], ['批准', 'Approve'], ['拒绝', 'Reject'], ['转为已报名', 'Move to Going'], ['手动签到', 'Check In'], ['标记为不参加', 'Mark Not Going'], ['BNBU 学生', 'BNBU Student'],
  ['已认证校园主办方', 'Verified campus host'], ['关注', 'Follow'], ['关注中', 'Following'], ['粉丝', 'followers'], ['该主办方的活动', 'Events by'], ['成员', 'Members'], ['精选成员', 'featured'], ['校园成员', 'Campus member'], ['来自社区', 'From the community'], ['一个主办方，多条校园路径。', 'One host, many campus paths.'], ['关注后，相关活动会进入 Campus Today，并在 Campus Graph 中建立可见连接。', 'Follow this host to bring related events into Campus Today and add a visible relationship to your Campus Graph.'], ['阅读相关帖子', 'Read related posts'], ['暂时没有即将开始的活动。', 'No upcoming events yet.'],
  ['主办方成为社群', 'Hosts become communities'], ['校园组织', 'Campus Organizations'], ['找到那些持续创造相聚理由的人。', 'Find the people who keep creating reasons to show up.'], ['已加入', 'Joined'], ['加入', 'Join'], ['加入组织', 'Join Organization'], ['认证组织', 'Verified Organization'], ['成员角色', 'Member roles'], ['一个仍有空间继续生长的社群。', 'A community with room to grow.'], ['查看全部', 'See all'], ['即将开始的活动', 'Upcoming Events'], ['帖子', 'Posts'], ['带领团队', 'Leads the team'], ['教师支持', 'Faculty support'], ['社群角色', 'Community role'], ['组织帖子位于社区中。', 'Organization posts live in Community.'], ['它们与组织保持连接，不会成为一条孤立的信息流。', 'They stay connected to this organization instead of becoming a separate feed.'], ['打开社区', 'Open Community'],
  ['行动 → 连接 → 归属', 'Activity → connection → belonging'], ['每一个社群都始于人们愿意一起做的一件事。', 'Every community begins with something people choose to do together.'], ['你今天的关系图', 'Your graph today'], ['个活跃连接', 'active connections'], ['活动', 'Activity'], ['组织', 'Organization'], ['连接', 'Connection'], ['社区', 'Community'], ['个人档案', 'Profile'], ['关系图', 'Graph'], ['个社群', 'communities'], ['教师连接', 'Faculty connection'], ['行动优先', 'Activity-first'], ['轻量社区', 'Light community'], ['未来模块', 'Future module'], ['探索', 'Explore'], ['现实生活', 'REAL LIFE'], ['成为', 'BECOMES'], ['你的故事', 'YOUR STORY'], ['平台逻辑', 'The platform logic'], ['校园生活应该不断积累。', 'Campus life should compound.'], ['报名活动不应只是在名单中增加一个名字。它可以介绍主办方、形成新连接、引发对话，并在 Campus Profile 中留下轨迹。', 'Registering for an event should do more than fill a list. It can introduce a host, form a new connection, spark a conversation, and leave a trace in your Campus Profile.'], ['从一场活动开始', 'Start with an event'],
  ['认识校园活动背后的社群。', 'Meet the communities behind campus activity.'], ['促成一次用心的对话。', 'Make one thoughtful conversation happen.'], ['围绕一项真实活动或兴趣找到同伴。', 'Find someone around a real activity or interest.'], ['扎根真实校园时刻的交流。', 'Campus conversations grounded in real moments.'], ['通过活动与陪伴把经验带回校园。', 'Bring experience back through events and mentoring.'],
  ['围绕一件真实的活动', 'Around a real activity'], ['寻找搭子', 'Find a Partner'], ['不是陌生人交友；是从一件具体想做的事开始。', 'Start with one concrete activity, not a stranger-matching feed.'], ['BNBU 认证学生 · Demo', 'BNBU verified student · Demo'], ['一起参加', 'Join together'], ['邀请已发送', 'Invite Sent'], ['该概念只发送邀请并建立待确认的 Graph 连接，不提供实时聊天。', 'This concept sends an invitation and creates a pending graph connection. It does not provide real-time chat.'],
  ['真实校园对象，轻量交流', 'Real campus objects, light conversation'], ['校园社区', 'Campus Community'], ['活动之后，连接和内容继续发生。', 'Connections and stories continue after the event.'], ['相关校园对象', 'Related campus object'], ['社区原则', 'Community principle'], ['线上内容跟随线下体验。', 'Online follows offline.'], ['帖子关联活动、组织或 Coffee Chat，让社区始终扎根校园生活。', 'Posts are tied to events, organizations, or Coffee Chats so the community stays grounded in campus life.'], ['热门校园对象', 'Trending objects'], ['评论', 'Comments'], ['发布评论', 'Post comment'], ['你的评论', 'Your comment'],
  ['校园', 'Campus'], ['运动', 'Sports'], ['学习', 'Study'], ['活动', 'Activities'], ['生活', 'Life'], ['2026级', '2026 Cohort'],
  ['经验回到校园', 'Experience returns to campus'], ['校友', 'Alumni'], ['活动、故事与陪伴都复用同一组 Campus Hub 对象。', 'Events, stories, and mentoring — built from the same Campus Hub objects.'], ['最有用的职业故事，是你能继续追问的故事。', 'The most useful career story is one you can ask questions about.'], ['可通过以下方式连接', 'Available through'], ['探索连接', 'Explore connection'], ['一个平台，克制地复用', 'One platform, reused thoughtfully'], ['活动 + 主办方 + Coffee Chat + 个人档案', 'Event + Host + Coffee Chat + Profile'], ['校友模块通过复用平台能力保持轻量，不成为另一套孤立系统。', 'The Alumni concept stays light by reusing the platform rather than becoming a separate system.'],
  ['教师主办方', 'Faculty hosts'], ['选择一场对话，而不只是一个时间。', 'Choose the conversation, not just the calendar.'], ['Coffee Chat · 特别校园活动', 'Coffee Chat · A special campus event'], ['一个好问题。', 'One good question.'], ['一场有价值的对话。', 'One useful conversation.'], ['和老师进行一次轻松、有准备的交流', 'Have a relaxed, prepared conversation with a teacher'], ['基于 Activity Engine', 'Built on the Activity Engine'], ['活动 + 教师 + 时间段 + 预约', 'Event + Teacher + Time Slot + Booking'], ['Coffee Chat 复用活动日历、通知、参与历史与 Graph 逻辑。', 'Coffee Chat reuses the same calendar, notifications, participation history, and graph logic as campus events.'], ['带着问题来，不必准备表演。', 'Come prepared, not rehearsed'], ['适合这场对话的话题', 'Good topics for this conversation'], ['安静的校园对话空间', 'Quiet campus conversation space'], ['选择 30 分钟时段', 'Choose a 30-minute slot'], ['可预约', 'Available'], ['已预约', 'Booked'], ['已满', 'Full'], ['取消', 'Cancel'], ['预约 Coffee Chat', 'Book Coffee Chat'], ['确认预约', 'Confirm Booking'], ['话题', 'Topic'],
  ['全部教师主办方', 'All faculty hosts'], ['Coffee Chat 是私密的一对一校园活动。预约后会同步更新“我的活动”、日历、Campus Journey 与 Graph。', 'Coffee Chats are private 1-on-1 campus events. Booking updates My Events, Calendar, Campus Journey, and Graph.'],
  ['未读', 'unread'], ['通知会带你回到对应的校园对象或操作。', 'Updates that lead back to a campus object or action.'], ['全部标为已读', 'Mark all as read'], ['此分类暂无通知。', 'No notifications in this category.'], ['全部通知已标为已读', 'All notifications marked as read'],
  ['活动通知', 'Events'], ['组织通知', 'Organizations'], ['体育通知', 'Sports'], ['社交通知', 'Social'],
  ['由参与组成的时间线。', 'A timeline made by participation.'], ['校园时刻', 'moments'], ['最新', 'Latest'], ['活跃活动', 'Active events'], ['已完成活动', 'Completed events'], ['社群关系', 'Communities'], ['连接节点', 'Connected nodes'], ['查看 Campus Graph', 'View Campus Graph'], ['你的 Campus Graph', 'Your Campus Graph'], ['查看行动如何成为连接', 'See how activity becomes connection'], ['你的校园关系正在生长。', 'Your campus relationships are growing.'], ['关系图', 'Campus Graph'], ['由活动、组织与对话生成，而不是单独维护的静态数据。', 'Derived from events, organizations, and conversations instead of maintained as separate static data.'], ['本学期', 'This semester'], ['校园连接', 'Campus connections'], ['你的社群', 'Your communities'], ['成员', 'Member'], ['加入校园组织，开始构建这部分个人档案。', 'Join a campus organization to start building this part of your profile.'], ['兴趣', 'Interests'], ['塑造推荐的兴趣信号', 'Signals shaping recommendations'], ['活动参与', 'Activities'], ['人际连接', 'Connections'], ['体育', 'Sports'], ['一张可读的参与关系图', 'A readable picture of participation'], ['每一条边都来自你的真实操作。', 'Every edge begins with something you actually did.'], ['重置视图', 'Reset View'], ['按节点类型筛选关系图', 'Filter graph by node type'], ['交互式校园关系图', 'Interactive campus relationship graph'], ['点击任一节点查看关系说明。', 'Click any node to explain the relationship.'], ['关系', 'Relationships'], ['选择一个节点查看详情。', 'Select a node to inspect it.'], ['如何阅读', 'How to read this'], ['实线表示活跃关系，虚线表示待确认关系。', 'Solid edges represent active relationships. Dashed edges are pending.'], ['实时派生', 'Live derivation'], ['这张关系图不是第二套 Mock 数据。', 'This graph is not a second set of Mock data.'], ['报名、签到、关注主办方、加入组织、预约 Coffee Chat、邀请搭子或创建活动；此视图都由同一份 Demo State 派生。', 'Register, check in, follow a host, join an organization, book a Coffee Chat, invite a partner, or create an event. This view is derived from that same Demo State.'],
  ['“我的大学生活正在逐渐形成一张 Campus Profile。”', '“My campus life is gradually becoming a Campus Profile.”'], ['课程相关', 'Course-related'], ['其他运动', 'Other sports'],
  ['找不到这条校园路径', 'Campus path not found'], ['这个时刻还不在地图上。', 'This moment is not on the map.'], ['返回 Campus Today，选择另一条连接。', 'Return to Campus Today and choose another connection.'], ['返回首页', 'Back Home'],
  ['工商管理学院', 'School of Management'], ['理工科技学院', 'School of Science and Technology'], ['创新创业中心', 'Innovation & Entrepreneurship Center'], ['人文社科学院', 'School of Humanities and Social Sciences'], ['通识教育学院', 'School of General Education'],
  ['运动', 'Sports'], ['学术', 'Academic'], ['社团', 'Organizations'], ['比赛', 'Competition'], ['讲座', 'Talks'], ['英语', 'English'], ['创业', 'Entrepreneurship'], ['校友', 'Alumni'], ['文化', 'Culture'], ['兴趣', 'Interest'], ['部门', 'Department'], ['学生组织', 'Student Organization'],
  ['市场营销', 'Marketing'], ['学业规划', 'Academic Planning'], ['研究方向', 'Research Direction'], ['AI 研究', 'AI Research'], ['技术职业', 'Technology Careers'], ['项目建议', 'Project Advice'], ['创业想法', 'Startup Ideas'], ['市场验证', 'Market Validation'], ['团队建设', 'Team Building'], ['英语表达', 'English Communication'], ['演讲', 'Public Speaking'], ['跨文化交流', 'Cross-cultural Communication'], ['大学适应', 'University Transition'], ['习惯设计', 'Habit Design'], ['体育参与', 'Sports Participation'],
  ['羽毛球', 'Badminton'], ['夜跑', 'Night Run'], ['跑步', 'Running'], ['健身', 'Fitness'], ['篮球', 'Basketball'], ['学习', 'Study'], ['比赛组队', 'Competition Team'], ['中级', 'Intermediate'], ['入门', 'Beginner'], ['休闲', 'Casual'], ['日常交流', 'Everyday Conversation'], ['产品设计', 'Product Design'], ['配速 6:30', '6:30 pace'], ['5km 慢跑', 'Easy 5 km'],
  ['陈雨晴', 'Yuqing Chen'], ['李明', 'Ming Li'], ['王嘉', 'Jia Wang'], ['罗楠', 'Nan Luo'], ['赵晨', 'Chen Zhao'], ['张老师', 'Professor Zhang'], ['李老师', 'Professor Li'], ['王老师', 'Professor Wang'], ['陈老师', 'Professor Chen'], ['赵老师', 'Professor Zhao'], ['李同学', 'Li'], ['王同学', 'Wang'], ['周同学', 'Zhou'], ['徐同学', 'Xu'], ['何同学', 'He'], ['陈同学', 'Chen'], ['罗同学', 'Luo'], ['郭同学', 'Guo'], ['刘同学', 'Liu'], ['林学长', 'Lin'], ['周学姐', 'Zhou'], ['陈学长', 'Chen'], ['刘学姐', 'Liu'], ['孙学长', 'Sun'], ['英语交流', 'English Exchange'],
  ['今天 20:00–22:00', 'Today · 20:00–22:00'], ['今晚 19:00', 'Tonight · 19:00'], ['周四 18:30', 'Thu · 18:30'], ['周三 16:00', 'Wed · 16:00'], ['周五 17:00', 'Fri · 17:00'], ['周六 10:00', 'Sat · 10:00'], ['周日 16:30', 'Sun · 16:30'], ['下周一 19:00', 'Next Mon · 19:00'],
  ['想打双打，节奏轻松但认真。', 'Looking for doubles partners for a relaxed but focused session.'], ['跟着 Running Club 一起跑，第一次来也可以。', 'Join the Running Club group; first-time runners are welcome.'], ['为 English Corner 提前热身。', 'A warm-up conversation before English Corner.'], ['一起准备 Marketing Case Night。', 'Prepare for Marketing Case Night together.'], ['45 分钟力量基础训练。', 'A 45-minute foundation strength session.'], ['组队参加 Product Design Jam。', 'Build a team for Product Design Jam.'], ['3×3 Open 前的轻松练习。', 'A relaxed practice before the 3×3 Open.'], ['固定每周一次，欢迎一起坚持。', 'A weekly run open to anyone who wants consistency.'], ['希望找 1–2 人', 'Looking for 1–2 people'], ['还差 1 人', '1 spot open'], ['希望找 2 人', 'Looking for 2 people'], ['希望找 1 人', 'Looking for 1 person'], ['还差设计 / 技术各 1 人', 'Need 1 designer and 1 developer'], ['还差 2 人', '2 spots open'], ['开放加入', 'Open to join'],
  ['有人今晚一起跑步吗？我准备参加 Campus Night Run，想找一个差不多配速的搭子。', 'Anyone up for a run tonight? I am joining Campus Night Run and looking for someone at a similar pace.'], ['AI Workshop 笔记模板已经整理好，第一次做 Agent 的同学可以先看任务拆解部分。', 'The AI Workshop notes template is ready. First-time Agent builders can start with the task breakdown.'], ['第一次参加 Coffee Chat，有什么建议？想和老师聊职业方向，但不想把它变成一次面试。', 'Any advice for a first Coffee Chat? I want to discuss career direction without turning it into an interview.'], ['羽毛球队招新开始啦。周四的 Open Night 可以直接来体验，不需要提前准备装备。', 'Badminton Team recruitment is open. Try Thursday Open Night; no equipment preparation is needed.'], ['Case Night 这次会把一份真实品牌挑战拆成消费者、定位和创意三段。', 'Case Night breaks a real brand challenge into audience, positioning, and creative direction.'], ['Courtyard Music Night 最后 3 个开放麦位置，欢迎原创、翻唱和器乐。', 'Courtyard Music Night has three open-mic spots left for originals, covers, or instruments.'], ['本周 Photo Walk 的主题是“校园里被忽略的蓝色”。手机就可以参加。', 'This Photo Walk looks for overlooked shades of blue around campus. A phone is enough.'], ['创业不是先写商业计划书。周五见面时我会分享我们如何找到第一个愿意付费的用户。', 'A startup does not begin with a business plan. On Friday I will share how we found our first paying customer.'], ['Volunteer Day 需要会摄影和会做双语引导的同学，各 2 名。', 'Volunteer Day needs two photographers and two bilingual guides.'], ['下周 Design Jam 会从校园真实服务场景出发，不要求任何设计软件经验。', 'Next week’s Design Jam starts from a real campus service and requires no design software experience.'],
  ['加入羽毛球队', 'Joined Badminton Team'], ['完成第一次体育打卡', 'Completed first Sports Check-in'], ['加入 Running Club', 'Joined Running Club'], ['参加新生校园漫步', 'Joined the new-student campus walk'], ['完成 5km 轻松跑', 'Completed an easy 5 km run'], ['关注 BNBU AI Club', 'Followed BNBU AI Club'], ['参加 English Corner', 'Attended English Corner'], ['加入 AI Club', 'Joined AI Club'], ['参加 Badminton Open Court', 'Attended Badminton Open Court'], ['认识新的跑步搭子', 'Met a new running partner'], ['完成 Marketing Case Sprint', 'Completed Marketing Case Sprint'], ['参与社区志愿活动', 'Joined Community Volunteer Day'], ['第一次 Coffee Chat', 'First Coffee Chat'], ['收藏 Product Design Jam', 'Saved Product Design Jam'], ['体育学时达到 16 小时', 'Reached 16 sports hours'],
  ['一群好奇的人分享一次体验，让一个校园时刻带来下一段连接。', 'Meet curious people, share an experience, and let one campus moment lead to the next.'], ['欢迎与相互认识', 'Welcome & introductions'], ['核心体验', 'Main experience'], ['自由连接时间', 'Open connection time'], ['校园生活', 'Campus Life'],
  ['构建你的第一个 AI Agent', 'Build Your First AI Agent'], ['把想法变成可运行 AI Agent 的实践工坊。带上电脑即可，不需要 Agent 开发经验。', 'A practical studio for turning an idea into a working AI agent. Bring a laptop; no prior agent-building experience is needed.'], ['共同构建', 'Build Together'], ['新手友好', 'Beginner Friendly'], ['19:30 — 欢迎与想法冲刺', '19:30 — Welcome and idea sprint'], ['19:50 — Agent 构建实验室', '19:50 — Agent building lab'], ['20:45 — Demo 分享与连接', '20:45 — Demo circle and connections'],
  ['五公里，一种校园节奏', 'Five kilometers, one campus rhythm'], ['面向所有水平的轻松 5 公里路线。一起热身，按配速小组出发，最后共同拉伸。', 'An easy-paced 5 km loop for every level. We warm up together, run in small pace groups, and finish with a stretch.'], ['全水平', 'All Levels'], ['18:50 — 蓝色跑道门集合', '18:50 — Meet by the blue track gate'], ['19:00 — 集体热身', '19:00 — Group warm-up'], ['19:10 — 配速小组出发', '19:10 — Pace groups depart'], ['20:00 — 放松整理', '20:00 — Cool-down'],
  ['会旅行的故事', 'Stories that travel'], ['开放球场，友好对打', 'Open courts, friendly rallies'], ['策略、故事与新队友', 'Strategy, stories, and new teammates'], ['从校园问题到第一个原型', 'From campus problem to first prototype'], ['90 分钟拆解一个品牌', 'Decode a brand in 90 minutes'], ['从 BNBU 到创业第一天', 'Founder Stories: From BNBU to Day One'], ['与林浩的一次真诚对话', 'An honest conversation with Lin Hao'], ['小舞台，大校园声音', 'Small stage, big campus voices'], ['用不同方式发现校园', 'Notice the campus differently'], ['设计一个更少浪费的星期', 'Design a lower-waste week'], ['为更友善的校园服务做原型', 'Prototype a kinder campus service'], ['在球场上组成队伍', 'Build a team on the court'], ['技术、信任与明天', 'Technology, trust, and tomorrow'], ['一个上午，产生实际影响', 'One morning, practical impact'], ['道路由行动走出来', 'Paths are made, not found'], ['可以握在手里的想法', 'Ideas you can hold'], ['带来一句话，带走一位朋友', 'Bring a phrase, leave with a friend'],
  ['一个一起构建有用且负责任 AI 的学生社群。', 'A student community for building useful, responsible AI together.'], ['社交跑、稳定进步，以及欢迎所有人的配速小组。', 'Social runs, steady progress, and a welcoming pace group for everyone.'], ['轻松练习、倾听、辩论并连接不同文化的空间。', 'A relaxed place to practise, listen, debate, and connect across cultures.'], ['BNBU 校队与开放羽毛球社群。', 'BNBU varsity and open-play badminton community.'], ['帮助校园想法成为周到实验与真实项目。', 'Helping campus ideas become thoughtful experiments and real ventures.'], ['为好奇的未来营销人准备案例、活动与对话。', 'Cases, campaigns, and conversations for curious future marketers.'], ['由学生发起、让校园生活更有连接的项目。', 'Student-led programs that make campus life more connected.'], ['把校友故事、陪伴与新机会带回校园。', 'Bringing alumni stories, mentorship, and new opportunities back to campus.'],
  ['工作坊', 'Workshops'], ['创作者', 'Builders'], ['健康生活', 'Wellbeing'], ['户外', 'Outdoors'], ['英语', 'English'], ['口语', 'Speaking'], ['训练', 'Training'], ['团队', 'Team'], ['设计', 'Design'], ['陪伴', 'Mentoring'], ['案例', 'Cases'], ['职业', 'Careers'], ['校园服务', 'Service'], ['校友陪伴', 'Mentorship'],
  ['张老师研究人们如何做出选择，以及品牌如何赢得信任。她的 Coffee Chat 实际、温暖，并由学生主导。', 'Professor Zhang studies how people make choices and how brands earn trust. Her Coffee Chats are practical, warm, and student-led.'], ['研究以人为本的 AI 系统与学习技术。', 'Works on human-centered AI systems and learning technologies.'], ['通过早期用户发现与第一次实验支持校园创业者。', 'Supports founders through early customer discovery and first experiments.'], ['帮助学生在不同文化与场景中清晰表达。', 'Helps students communicate with clarity across cultures and contexts.'], ['关注身心健康、主动学习与可持续校园生活。', 'Interested in wellbeing, active learning, and sustainable campus life.'], ['副教授', 'Associate Professor'], ['助理教授', 'Assistant Professor'], ['驻校创业导师', 'Entrepreneur in Residence'], ['讲师', 'Lecturer'], ['高级讲师', 'Senior Lecturer'], ['消费者行为', 'Consumer Behavior'], ['计算机科学', 'Computer Science'], ['创新', 'Innovation'], ['沟通', 'Communication'], ['语言', 'Language'], ['教育', 'Education'], ['周三 15:00–17:00', 'Wednesday 15:00–17:00'], ['周五 14:00–16:00', 'Friday 14:00–16:00'], ['周二 16:00–18:00', 'Tuesday 16:00–18:00'], ['周四 13:00–15:00', 'Thursday 13:00–15:00'], ['周一 10:00–12:00', 'Monday 10:00–12:00'],
  ['与开放的学生社群一起构建有用的 AI 项目。', 'Build useful AI projects with an open student community.'], ['欢迎每一种配速的校园跑。', 'Welcoming campus runs for every pace.'], ['训练、开放球场与校队比赛。', 'Training, open court nights, and varsity competition.'], ['通过真实对话练习沟通。', 'Practice communication through real conversations.'], ['把课堂想法变成案例、活动与连接。', 'Turn class ideas into cases, campaigns, and connections.'], ['通过结伴漫步与视觉故事看见校园生活。', 'See campus life through shared walks and visual stories.'], ['由学生推动的服务、文化与校园项目。', 'Student-led service, culture, and campus programs.'], ['属于实验、创业者与导师的校园空间。', 'A campus home for experiments, founders, and mentors.'], ['组织者', 'Organizer'], ['队长', 'Captain'], ['顾问', 'Advisor'],
  ['创业创始人', 'Startup Founder'], ['产品经理', 'Product Manager'], ['品牌策略师', 'Brand Strategist'], ['AI 研究员', 'AI Researcher'], ['社会影响力负责人', 'Social Impact Lead'], ['在校园期间建立了他的第一个用户社群。', 'Built his first customer community while still on campus.'], ['把用户信号转化为简单的产品决策。', 'Turns customer signals into simple product decisions.'], ['在文化、策略与新兴消费品牌之间工作。', 'Works across culture, strategy, and emerging consumer brands.'], ['研究可靠 AI 系统，并陪伴学生创作者。', 'Explores reliable AI systems and mentors student builders.'], ['设计连接本地社区与年轻人的项目。', 'Designs programs that connect local communities and young people.'], ['创业分享会', 'Founder Talk'],
  ['AI Agent Workshop 已开放报名', 'AI Agent Workshop is open'], ['周三工作坊现已开放报名。', 'Registration is now available for the Wednesday workshop.'], ['Campus Night Run 即将开始', 'Campus Night Run starts soon'], ['18:50 在蓝色跑道门集合。', 'Meet at the blue track gate at 18:50.'], ['新的 Coffee Chat 时段', 'New Coffee Chat slots'], ['张老师开放了周三下午的时段。', 'Professor Zhang opened Wednesday afternoon slots.'], ['Running Club 发布了新活动', 'Running Club posted a new event'], ['周末日出跑已加入日历。', 'A weekend sunrise run is now on the calendar.'], ['羽毛球训练更新', 'Badminton training update'], ['周四训练调整至 3 号场。', 'Thursday training moves to Court 3.'], ['搭子推荐', 'Partner suggestion'], ['一位配速相近的同学今晚也会参加。', 'A student with a similar running pace is joining tonight.'], ['Startup Meetup 需要审批', 'Startup Meetup needs approval'], ['你的申请将由主办方审核。', 'Your request will be reviewed by the host.'], ['Badminton Night 候补', 'Badminton Night waitlist'], ['你目前排在候补第 3 位。', 'You are currently number 3 on the waitlist.'], ['AI Club 每周摘要', 'AI Club weekly digest'], ['三个新工作坊符合你的兴趣。', 'Three new workshops match your interests.'], ['校园社区有新回复', 'New reply in Campus Community'], ['李明回复了你关于 AI Workshop 的问题。', 'Ming replied to your question about AI Workshop.'], ['收藏活动提醒', 'Saved event reminder'], ['Product Design Jam 报名即将截止。', 'Product Design Jam registration closes soon.'], ['准备一个好问题', 'Prepare one good question'], ['一份帮助你进行有效教师对话的简短指南。', 'A simple guide for a useful faculty conversation.'],
  ['10 分钟前', '10 min ago'], ['22 分钟前', '22 min ago'], ['1 小时前', '1 h ago'], ['2 小时前', '2 h ago'], ['3 小时前', '3 h ago'], ['4 小时前', '4 h ago'], ['昨天', 'Yesterday'], ['2 天前', '2 days ago'], ['3 天前', '3 days ago'], ['4 天前', '4 days ago'], ['12 分钟前', '12 min ago'], ['34 分钟前', '34 min ago'], ['5 小时前', '5 h ago'],
  ['2026年10月', 'October 2026'],
  ['今天', 'TODAY'], ['10月18日', 'OCT 18'], ['10月19日', 'OCT 19'], ['10月20日', 'OCT 20'], ['10月21日', 'OCT 21'], ['10月22日', 'OCT 22'], ['10月23日', 'OCT 23'], ['10月24日', 'OCT 24'], ['10月25日', 'OCT 25'], ['10月26日', 'OCT 26'], ['10月27日', 'OCT 27'], ['10月28日', 'OCT 28'], ['10月29日', 'OCT 29'], ['10月30日', 'OCT 30'], ['周三', 'WED'], ['周四', 'THU'], ['周五', 'FRI'], ['周六', 'SAT'], ['周日', 'SUN'], ['周一', 'MON'], ['周二', 'TUE'],
  ['成员 · 羽毛球队', 'Member · Badminton Team'], ['GEPE101 · 1.5 小时', 'GEPE101 · 1.5 hours'], ['新的每周校园节奏', 'A new weekly campus rhythm'], ['认识了 4 位新同学', 'Met 4 new classmates'], ['体育场 · 42 分钟', 'Sports Field · 42 minutes'], ['相关工作坊已进入推荐', 'Workshops now appear in recommendations'], ['话题：来自家乡的故事', 'Topic: stories from home'], ['成员 · 创作者小组', 'Member · Builders group'], ['完成 3 场双打', 'Played 3 doubles matches'], ['通过校园活动建立连接', 'Connected through a campus activity'], ['团队展示 · T4', 'Team presentation · T4'], ['双语欢迎台', 'Bilingual welcome desk'], ['与陈老师聊职业问题', 'Career questions with Professor Chen'], ['留待下周参加', 'Saved for next week'], ['课程相关活动还差 4 小时', '4 hours remaining in course-related activity'],
  ['校园夜跑', 'Campus Night Run'], ['羽毛球训练', 'Badminton Practice'], ['力量训练', 'Strength Session'], ['校园漫步', 'Campus Walk'], ['校园晨跑', 'Morning Campus Run'], ['BNBU 体育场', 'BNBU Sports Field'], ['体育中心 3 号场', 'Sports Center Court 3'], ['健身工作室', 'Fitness Studio'], ['BNBU 校园环线', 'BNBU Campus Loop'], ['体育中心 2 号场', 'Sports Center Court 2'],
  ['体育教育 · 16/20 小时', 'Physical Education · 16/20h'], ['持续增长的学术与创客兴趣', 'A growing academic and maker interest'], ['运动与身心健康', 'Sports and wellbeing'], ['学习与职业兴趣', 'Study and career interest'], ['待确认的活动连接', 'Pending activity connection'], ['由你主办', 'Hosted by you'], ['校园搭子', 'Campus Partner'], ['教师导师', 'Faculty Mentor'],
]

const lookup = {
  zh: new Map(pairs.map(([zh, en]) => [en, zh])),
  en: new Map(pairs.map(([zh, en]) => [zh, en])),
}

const englishOnly = new Map([
  ['晴', 'YQ'], ['雨', 'YU'], ['陈', 'CY'], ['李', 'LM'], ['王', 'WJ'], ['罗', 'LN'], ['赵', 'ZC'], ['徐', 'XU'], ['何', 'HE'], ['郭', 'GU'], ['刘', 'LIU'], ['林', 'LIN'], ['周', 'ZH'], ['张', 'ZZ'], ['孙', 'SUN'], ['明', 'M'], ['嘉', 'J'], ['楠', 'N'],
])
const chineseOnly = new Map([
  ['YQ', '晴'], ['YU', '雨'], ['CY', '陈'], ['LM', '李'], ['WJ', '王'], ['LN', '罗'], ['ZC', '赵'], ['XU', '徐'], ['HE', '何'], ['GU', '郭'], ['LIU', '刘'], ['LIN', '林'], ['ZH', '周'], ['ZZ', '张'], ['SUN', '孙'], ['M', '明'], ['J', '嘉'], ['N', '楠'],
])

const patterns: Record<Language, ReadonlyArray<readonly [RegExp, string]>> = {
  zh: [
    [/^(\d+) going$/, '$1 人参加'], [/^(\d+) attending$/, '$1 人参加'], [/^(\d+) people are joining$/, '$1 人参加'], [/^(\d+) spots available$/, '剩余 $1 个名额'],
    [/^(\d+) curated moments$/i, '$1 个精选活动'], [/^(\d+) communities$/i, '$1 个社群'], [/^(\d+) connected nodes$/, '$1 个连接节点'], [/^(\d+) active connections$/, '$1 个活跃连接'], [/^(\d+) nodes · (\d+) relationships$/, '$1 个节点 · $2 条关系'], [/^(\d+) course-related hours remaining$/, '课程相关还差 $1 小时'], [/^(\d+) upcoming events$/, '$1 个即将开始的活动'], [/^(\d+) events$/, '$1 个活动'], [/^(\d+) members$/, '$1 位成员'], [/^(\d+) slots$/, '$1 个时段'], [/^(\d+) spots left$/, '剩余 $1 个名额'],
    [/^Nothing in (.+) yet\.$/, '$1 暂无内容。'], [/^Events by (.+)$/, '$1 的活动'], [/^Led by (.+)$/, '负责人：$1'], [/^Following (.+)$/, '已关注 $1'], [/^Joined (.+)$/, '已加入 $1'], [/^Left (.+)$/, '已退出 $1'], [/^Unfollowed (.+)$/, '已取消关注 $1'], [/^Invite sent to (.+)$/, '已向 $1 发送邀请'], [/^Coffee Chat confirmed with (.+)$/, '已确认与 $1 的 Coffee Chat'], [/^← All faculty hosts$/, '← 全部教师主办方'],
    [/^Following · (.+)$/, '关注中 · $1'], [/^Member · (.+)$/, '成员 · $1'], [/^Coffee Chat · (.+)$/, 'Coffee Chat · $1'], [/^Partner (\d+)$/, '搭子 $1'], [/(\d{4}) Cohort/, '$1级'], [/^(用户|活动|组织|教师|兴趣|课程|校友) node$/, '$1节点'], [/^← My Campus$/, '← 我的校园'],
    [/^Events ·/, '活动 ·'], [/^Organizations ·/, '组织 ·'], [/^Sports ·/, '体育 ·'], [/^Social ·/, '社交 ·'], [/^Activities$/, '活动'], [/^Life$/, '生活'], [/^Study$/, '学习'], [/^BNBU \/ Workshop$/, 'BNBU / 工作坊'],
  ],
  en: [
    [/^(\d+) 人参加$/, '$1 attending'], [/^剩余 (\d+) 个名额$/, '$1 spots available'], [/^(\d+) 个精选活动$/, '$1 curated moments'], [/^(\d+) 个连接节点$/, '$1 connected nodes'], [/^(\d+) 个活跃连接$/, '$1 active connections'], [/^(\d+) 个节点 · (\d+) 条关系$/, '$1 nodes · $2 relationships'], [/^课程相关还差 (\d+) 小时$/, '$1 course-related hours remaining'], [/^(\d+) 个即将开始的活动$/, '$1 upcoming events'], [/^(\d+) 个活动$/, '$1 events'], [/^(\d+) 位成员$/, '$1 members'], [/^(\d+) 个时段$/, '$1 slots'], [/^已关注 (.+)$/, 'Following $1'], [/^已加入 (.+)$/, 'Joined $1'], [/^已退出 (.+)$/, 'Left $1'], [/^已取消关注 (.+)$/, 'Unfollowed $1'], [/^已向 (.+) 发送邀请$/, 'Invite sent to $1'],
    [/^关注中 · (.+)$/, 'Following · $1'], [/^成员 · (.+)$/, 'Member · $1'], [/^搭子 (\d+)$/, 'Partner $1'], [/(\d{4})级/, '$1 Cohort'], [/^(用户|活动|组织|教师|兴趣|课程|校友)节点$/, '$1 node'], [/^← 我的校园$/, '← My Campus'],
    [/工商管理学院/g, 'School of Management'], [/理工科技学院/g, 'School of Science and Technology'], [/创新创业中心/g, 'Innovation & Entrepreneurship Center'], [/人文社科学院/g, 'School of Humanities and Social Sciences'], [/通识教育学院/g, 'School of General Education'],
  ],
}

export function localizeLegacyText(value: string, language: Language) {
  const translated = lookup[language].get(value)
  if (translated) return translated
  if (language === 'en' && englishOnly.has(value)) return englishOnly.get(value) ?? value
  if (language === 'zh' && chineseOnly.has(value)) return chineseOnly.get(value) ?? value
  return patterns[language].reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value)
}
