import { ArrowRight, Check, ChevronRight, CircleAlert, FileCheck2, Newspaper, ShieldCheck, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { makeId, type Verification } from './model'
import { useV2 } from './useV2'
import { Drawer, Empty, PageHeading, SectionHeading } from './ui'

const kindName = { student: '学生', club: '学生社团成员', official: '官方机构' }
const statusName = { pending: '待审核', approved: '已通过', rejected: '已驳回' }

export function AdminDashboard() {
  const { state } = useV2()
  const pendingPosts = state.posts.filter((post) => post.status === 'pending')
  const pendingComments = state.posts.flatMap((post) => post.comments.filter((comment) => comment.status === 'pending').map((comment) => ({ ...comment, postTitle: post.title })))
  const pendingVerifications = state.verifications.filter((item) => item.status === 'pending')
  const metrics = [
    { label: '内容待审', value: pendingPosts.length + pendingComments.length, detail: `帖子 ${pendingPosts.length} · 评论 ${pendingComments.length}`, path: '/v2/admin/moderation', icon: FileCheck2 },
    { label: '认证待审', value: pendingVerifications.length, detail: '学生 / 社团成员 / 官方', path: '/v2/admin/verifications', icon: ShieldCheck },
    { label: '校园社区', value: state.posts.filter((post) => post.status === 'visible').length, detail: '当前可见帖子', path: '/v2/admin/moderation', icon: Newspaper },
  ]
  return <div className="v2-page"><PageHeading eyebrow="OPERATIONS OVERVIEW" title="运营工作台" description="认证与内容审核在同一套演示数据里协作。"/><div className="v2-admin-metrics">{metrics.map(({ icon: Icon, ...metric }, index) => <Link to={metric.path} key={metric.label} style={{ animationDelay: `${index * 65}ms` }}><span><Icon size={20}/>{metric.label}</span><strong>{metric.value}</strong><small>{metric.detail}</small><ArrowRight size={16}/></Link>)}</div><div className="v2-admin-grid"><section className="v2-panel v2-list-panel"><SectionHeading title="内容审核待办" detail="新帖与评论先在这里检查" action={<Link to="/v2/admin/moderation">查看全部 <ArrowRight size={15}/></Link>}/>{pendingPosts.slice(0, 3).map((post) => <Link to="/v2/admin/moderation" className="v2-admin-queue-row" key={post.id}><span className="v2-queue-icon"><Newspaper size={18}/></span><span><strong>{post.title}</strong><small>帖子 · {post.author}</small></span><span className="v2-status-chip is-pending">待审</span><ChevronRight size={16}/></Link>)}{pendingComments.slice(0, 2).map((comment) => <Link to="/v2/admin/moderation" className="v2-admin-queue-row" key={comment.id}><span className="v2-queue-icon"><CircleAlert size={18}/></span><span><strong>{comment.body}</strong><small>评论 · {comment.postTitle}</small></span><span className="v2-status-chip is-pending">待审</span><ChevronRight size={16}/></Link>)}{!pendingPosts.length && !pendingComments.length && <Empty icon={Check} title="内容队列已处理完"/>}</section><section className="v2-panel v2-list-panel"><SectionHeading title="认证审核待办" detail="核对申请类型与说明" action={<Link to="/v2/admin/verifications">查看全部 <ArrowRight size={15}/></Link>}/>{pendingVerifications.slice(0, 4).map((item) => <Link to="/v2/admin/verifications" className="v2-admin-queue-row" key={item.id}><span className="v2-queue-icon"><ShieldCheck size={18}/></span><span><strong>{item.organization}</strong><small>{kindName[item.kind]} · {item.name}</small></span><ChevronRight size={16}/></Link>)}{!pendingVerifications.length && <Empty icon={Check} title="认证队列已处理完"/>}</section></div></div>
}

export function AdminVerifications() {
  const { state, setState } = useV2()
  const [filter, setFilter] = useState<'all' | 'pending' | 'approved' | 'rejected'>('pending')
  const [kind, setKind] = useState<'all' | Verification['kind']>('all')
  const [selected, setSelected] = useState<string | null>(null)
  const [note, setNote] = useState('')
  const items = state.verifications.filter((item) => (filter === 'all' || item.status === filter) && (kind === 'all' || item.kind === kind))
  const current = state.verifications.find((item) => item.id === selected)
  const decide = (item: Verification, approve: boolean) => { if (state.role !== 'admin' || (!approve && item.status === 'approved' && !note.trim())) return; setState((value) => ({ ...value, verifications: value.verifications.map((entry) => entry.id === item.id ? { ...entry, status: approve ? 'approved' : 'rejected', reviewNote: note.trim() || (approve ? '认证已通过' : '请补充或核对申请资料') } : entry), notifications: item.name === '陈雨晴' ? [{ id: makeId(), title: approve ? '身份认证已通过' : '身份认证未通过', body: item.organization, path: '/v2/me?tab=verification', read: false, date: '刚刚' }, ...value.notifications] : value.notifications })); setSelected(null); setNote('') }
  return <div className="v2-page"><PageHeading eyebrow="IDENTITY REVIEW" title="认证审核" description="区分学生、学生社团成员和官方机构，保留清楚的审核状态。"/><section className="v2-panel v2-list-panel"><SectionHeading title="认证申请" detail={`${items.length} 条结果`}/><div className="v2-toolbar"><div className="v2-filter-pills">{([['pending', '待审核'], ['approved', '已通过'], ['rejected', '已驳回'], ['all', '全部']] as const).map(([key, label]) => <button type="button" className={filter === key ? 'is-active' : ''} onClick={() => setFilter(key)} key={key}>{label}</button>)}</div><select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)} aria-label="认证类型"><option value="all">全部类型</option><option value="student">学生</option><option value="club">学生社团成员</option><option value="official">官方机构</option></select></div><div className="v2-row-list">{items.map((item) => <button type="button" className="v2-verification-row" onClick={() => { setSelected(item.id); setNote(item.status === 'approved' ? '' : item.reviewNote) }} key={item.id}><span className="v2-notice-icon"><ShieldCheck size={20}/></span><span><small>{kindName[item.kind]} · {item.date}</small><strong>{item.organization}</strong><em>{item.name} · {item.note}</em></span><span className={`v2-status-chip ${item.status === 'approved' ? 'is-success' : item.status === 'pending' ? 'is-pending' : ''}`}>{statusName[item.status]}</span><ChevronRight size={17}/></button>)}</div>{!items.length && <Empty icon={ShieldCheck} title="当前筛选下没有申请"/>}</section>{current && <Drawer title={current.organization} eyebrow={`${kindName[current.kind]}认证 · ${statusName[current.status]}`} onClose={() => setSelected(null)}><div className="v2-fact-list"><span>申请人：{current.name}</span><span>提交时间：{current.date}</span></div><p className="v2-detail-lead">{current.note}</p>{current.status === 'pending' ? <><label className="v2-drawer-label">审核备注<textarea rows={4} value={note} onChange={(event) => setNote(event.target.value)} placeholder="可填写通过说明或驳回原因"/></label><div className="v2-detail-actions"><button type="button" className="v2-button v2-button-secondary" onClick={() => decide(current, false)}><X size={16}/> 驳回</button><button type="button" className="v2-button v2-button-primary" onClick={() => decide(current, true)}><Check size={16}/> 通过</button></div></> : <div className="v2-info-box">审核备注：{current.reviewNote || '无'}{current.kind === 'club' && current.status === 'approved' && <><label className="v2-drawer-label">撤销原因<textarea value={note} onChange={(event) => setNote(event.target.value)} required/></label><button type="button" disabled={!note.trim()} className="v2-button v2-button-secondary" onClick={() => decide(current, false)}>撤销社团成员认证</button></>}</div>}</Drawer>}</div>
}

type ModerationItem = { id: string; kind: 'post' | 'comment'; title: string; body: string; author: string; status: 'visible' | 'pending' | 'hidden'; parentId?: string }
export function AdminModeration() {
  const { state, setState } = useV2()
  const [status, setStatus] = useState<'pending' | 'visible' | 'hidden' | 'all'>('pending')
  const [kind, setKind] = useState<'all' | 'post' | 'comment'>('all')
  const [selected, setSelected] = useState<string | null>(null)
  const all: ModerationItem[] = [
    ...state.posts.map((post) => ({ id: post.id, kind: 'post' as const, title: post.title, body: post.body, author: post.author, status: post.status })),
    ...state.posts.flatMap((post) => post.comments.map((comment) => ({ id: comment.id, kind: 'comment' as const, title: `评论 · ${post.title}`, body: comment.body, author: comment.author, status: comment.status, parentId: post.id }))),
  ]
  const items = all.filter((item) => (status === 'all' || item.status === status) && (kind === 'all' || item.kind === kind))
  const current = all.find((item) => item.id === selected)
  const moderate = (item: ModerationItem, next: 'visible' | 'hidden') => { setState((value) => ({ ...value, posts: value.posts.map((post) => item.kind === 'post' ? post.id === item.id ? { ...post, status: next } : post : post.id === item.parentId ? { ...post, comments: post.comments.map((comment) => comment.id === item.id ? { ...comment, status: next } : comment) } : post), notifications: item.author === '陈雨晴' ? [{ id: makeId(), title: next === 'visible' ? '社区内容已通过审核' : '社区内容未通过审核', body: item.title, path: '/v2/community', read: false, date: '刚刚' }, ...value.notifications] : value.notifications })); setSelected(null) }
  return <div className="v2-page"><PageHeading eyebrow="CONTENT REVIEW" title="内容审核" description="统一查看社区帖子与评论的发布状态。"/><section className="v2-panel v2-list-panel"><SectionHeading title="审核队列" detail={`${items.length} 条内容`}/><div className="v2-toolbar"><div className="v2-filter-pills">{([['pending', '待审核'], ['visible', '已展示'], ['hidden', '已下架'], ['all', '全部']] as const).map(([key, label]) => <button type="button" className={status === key ? 'is-active' : ''} onClick={() => setStatus(key)} key={key}>{label}</button>)}</div><select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)} aria-label="内容类型"><option value="all">帖子与评论</option><option value="post">帖子</option><option value="comment">评论</option></select></div><div className="v2-row-list">{items.map((item) => <button type="button" className="v2-verification-row" key={item.id} onClick={() => setSelected(item.id)}><span className="v2-notice-icon"><Newspaper size={19}/></span><span><small>{item.kind === 'post' ? '帖子' : '评论'} · {item.author}</small><strong>{item.title}</strong><em>{item.body}</em></span><span className={`v2-status-chip ${item.status === 'visible' ? 'is-success' : item.status === 'pending' ? 'is-pending' : ''}`}>{item.status === 'pending' ? '待审' : item.status === 'visible' ? '展示中' : '已下架'}</span><ChevronRight size={17}/></button>)}</div>{!items.length && <Empty icon={FileCheck2} title="当前队列没有内容"/>}</section>{current && <Drawer title={current.title} eyebrow={`${current.kind === 'post' ? '帖子' : '评论'} · ${current.author}`} onClose={() => setSelected(null)}><p className="v2-detail-lead">{current.body}</p><div className="v2-info-box">此页仅用于演示审核交互，不进行自动内容判断。</div><div className="v2-detail-actions">{current.status !== 'hidden' && <button type="button" className="v2-button v2-button-secondary" onClick={() => moderate(current, 'hidden')}><X size={16}/> {current.status === 'pending' ? '驳回' : '下架'}</button>}{current.status !== 'visible' && <button type="button" className="v2-button v2-button-primary" onClick={() => moderate(current, 'visible')}><Check size={16}/> {current.status === 'hidden' ? '恢复展示' : '通过审核'}</button>}</div></Drawer>}</div>
}
