import { useEffect, useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, GraduationCap, UsersRound } from 'lucide-react'
import { useV2 } from './useV2'
import { PageHeading, Empty, SectionHeading } from './ui'
import { alumniData, currentAlumniActor, followAlumni, bookingStatus, cancelAlumniBooking, editAlumniProfile, addAlumniSlot, closeAlumniSlot, publishAlumniPost } from './alumniPolicy'
import type { V2State } from './model'

const alumniTime = (value: string) => new Date(value).toLocaleString('zh-CN', { month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })
const alumniStatus = { pending: '待校友确认', confirmed: '已确认', rejected: '已拒绝', withdrawn: '已撤回', cancelled: '已取消', expired: '已过期', unavailable: '时段已被预约' }

export function V2Alumni() {
  const { state, setState } = useV2(), data = alumniData(state), actor = currentAlumniActor(state)
  const [params] = useSearchParams(), view = params.get('view') ?? 'discover'
  const [query, setQuery] = useState(''), [direction, setDirection] = useState('全部'), [followed, setFollowed] = useState(false)
  const [error, setError] = useState(''), [success, setSuccess] = useState('')
  const [reason, setReason] = useState('')
  const [, tick] = useState(0)
  useEffect(() => { const timer = window.setInterval(() => tick(n => n + 1), 30000); return () => window.clearInterval(timer) }, [])
  useEffect(() => { setError(''); setSuccess('') }, [view, params])
  const mine = data.profiles.find(item => item.owner === actor.id)
  const person = data.profiles.find(item => item.id === params.get('person') && item.status === 'approved')
  function act(update: (value: V2State) => V2State, message = '') {
    try { const next = update(state); setState(next); setError(''); setSuccess(message) } catch (cause) { setError(cause instanceof Error ? cause.message : '操作失败，请重试。'); setSuccess('') }
  }
  const people = data.profiles.filter(item => item.status === 'approved' && (direction === '全部' || item.direction === direction) && (!followed || data.follows.some(f => f.student === actor.id && f.alumniId === item.id)) && `${item.name} ${item.major} ${item.graduationYear} ${item.city} ${item.experience} ${item.topics}`.toLowerCase().includes(query.trim().toLowerCase()))
  const posts = state.posts.filter(post => post.alumniId && (post.status === 'visible' || post.status === 'pending' && post.alumniId === mine?.id) && (!person || post.alumniId === person.id))
  function saveProfile(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const f = new FormData(event.currentTarget)
    act(s => editAlumniProfile(s, actor, { city: String(f.get('city')), direction: f.get('direction') as '升学' | '就业', experience: String(f.get('experience')), topics: String(f.get('topics')), bio: String(f.get('bio')), accepting: f.get('accepting') === 'on' }), '校友资料已保存。')
  }
  function addSlot(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget, f = new FormData(form)
    act(s => addAlumniSlot(s, actor, { startAt: String(f.get('start')), endAt: String(f.get('end')), location: String(f.get('location')) }), '交流时段已开放。')
  }
  function publish(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const f = new FormData(event.currentTarget)
    act(s => publishAlumniPost(s, actor, String(f.get('title')), String(f.get('body')), f.get('topic') as '升学' | '就业'), '经验分享已提交，等待管理员审核。')
  }
  return <div className="v2-page v2-alumni-page"><Link className="v2-text-button" to="/v2"><ArrowLeft size={16}/> 返回首页</Link><PageHeading eyebrow="ALUMNI CONNECTIONS" title="校友同行" description="向走过这段路的人请教，让校园里的连接延续。" action={<Link className="v2-button v2-button-secondary" to="/v2/alumni?view=manage">{mine?.status === 'approved' ? '我的校友资料' : '校友认证'}</Link>}/>
    <nav className="v2-tabs" aria-label="校友板块"><Link className={view === 'discover' ? 'is-active' : ''} to="/v2/alumni">寻找校友</Link><Link className={view === 'stories' ? 'is-active' : ''} to="/v2/alumni?view=stories">经验分享</Link><Link className={view === 'bookings' ? 'is-active' : ''} to="/v2/alumni?view=bookings">我的交流</Link></nav>
    {error && <p className="v2-info-box" role="alert">{error}</p>}{success && <p className="v2-info-box" role="status">{success}</p>}
    {view === 'discover' && !person && <><section className="v2-alumni-intro"><GraduationCap size={32}/><div><h2>从一个问题，开始一次连接</h2><p>升学准备、第一份实习、职业选择，都可以与校友聊聊。</p><small>以下校友、经历与时段为本地演示资料。</small></div></section><section className="v2-panel v2-list-panel"><div className="v2-toolbar"><input className="v2-alumni-search" aria-label="搜索校友" placeholder="姓名、专业、年份、城市或行业" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="交流方向" value={direction} onChange={e => setDirection(e.target.value)}><option>全部</option><option>升学</option><option>就业</option></select><label className="v2-alumni-follow-filter"><input type="checkbox" checked={followed} onChange={e => setFollowed(e.target.checked)}/>只看已关注</label></div><div className="v2-alumni-grid">{people.map(item => <article className="v2-alumni-card" key={item.id}><span className="v2-avatar">{item.name.slice(0, 1)}</span><span className="v2-status-chip is-success">认证校友</span><h3>{item.name}</h3><p>{item.graduationYear} 届 · {item.major}</p><p>{item.city} · {item.experience}</p><div className="v2-alumni-topics">{item.topics}</div><div className="v2-detail-actions"><Link className="v2-button v2-button-primary" to={`/v2/alumni?person=${item.id}`}>了解校友 <ArrowRight size={15}/></Link>{item.owner !== actor.id && <button className="v2-button v2-button-secondary" onClick={() => act(s => followAlumni(s, actor, item.id))}>{data.follows.some(f => f.student === actor.id && f.alumniId === item.id) ? '取消关注' : '关注'}</button>}</div></article>)}</div>{!people.length && <Empty icon={UsersRound} title="暂无符合条件的校友" description="试试其他关键词，或取消已关注筛选。"/>}</section></>}
    {view === 'discover' && person && <><Link className="v2-text-button" to="/v2/alumni"><ArrowLeft size={16}/> 返回校友列表</Link><section className="v2-panel v2-list-panel"><SectionHeading title={person.name} detail={`${person.graduationYear} 届 · ${person.major} · ${person.city}`}/><span className="v2-status-chip is-success">校友身份已认证</span><p>{person.experience}</p><p>{person.bio}</p><p>可交流：{person.topics}</p><small>升学和工作经历由本人提供，校友认证不代表经历均已核验。</small>{person.owner !== actor.id && <div className="v2-detail-actions"><button className="v2-button v2-button-secondary" onClick={() => act(s => followAlumni(s, actor, person.id))}>{data.follows.some(f => f.student === actor.id && f.alumniId === person.id) ? '取消关注' : '关注校友'}</button></div>}</section><section className="v2-panel v2-list-panel"><SectionHeading title="Coffee Chat" detail="提交交流问题后，等待校友确认"/><AlumniAppointmentArea personId={person.id}/></section></>}
    {(view === 'stories' || person) && <section className="v2-panel v2-list-panel"><SectionHeading title="升学与就业经验" detail="与校园社区共用收藏、评论和审核"/>{posts.map(post => <Link className="v2-saved-row" to={`/v2/community?item=${post.id}`} key={post.id}><GraduationCap size={20}/><span><strong>{post.title}</strong><small>{post.author} · {post.board} · {post.status === 'pending' ? '待审核' : post.date}</small></span><ArrowRight size={16}/></Link>)}{!posts.length && <Empty icon={GraduationCap} title="还没有经验分享"/>}{mine?.status === 'approved' && <form className="v2-form" onSubmit={publish}><SectionHeading title="分享我的经历"/><label>方向<select name="topic"><option>升学</option><option>就业</option></select></label><label>标题<input name="title" maxLength={80} required/></label><label>正文<textarea name="body" maxLength={1000} rows={5} required/></label><button className="v2-button v2-button-primary">提交审核</button></form>}</section>}
    {view === 'bookings' && <><section className="v2-panel v2-list-panel"><SectionHeading title="交流通知"/>{data.notices.filter(item => item.recipient === actor.id).slice(0, 10).map(item => <p key={item.id}>{item.body} <small>{alumniTime(item.at)}</small>{!item.read && <button className="v2-text-button" onClick={() => act(s => ({ ...s, alumni: { ...alumniData(s), notices: alumniData(s).notices.map(n => n.id === item.id && n.recipient === actor.id ? { ...n, read: true } : n) } }))}>标为已读</button>}</p>)}{!data.notices.some(item => item.recipient === actor.id) && <p>暂无交流通知。</p>}</section><section className="v2-panel v2-list-panel"><SectionHeading title="我的申请与预约"/><label className="v2-drawer-label">取消原因（已确认预约必填）<input maxLength={300} value={reason} onChange={e => setReason(e.target.value)} placeholder="说明取消原因"/></label>{data.bookings.filter(item => item.student === actor.id).map(item => { const slot = data.slots.find(s => s.id === item.slotId)!, alumnus = data.profiles.find(p => p.id === slot.alumniId)!, status = bookingStatus(data, item); return <article className="v2-alumni-booking" key={item.id}><h3>与{alumnus.name}的 Coffee Chat</h3><p>{alumniTime(slot.startAt)} — {alumniTime(slot.endAt)}</p><p>{slot.location}</p><p>{item.question}</p><span className="v2-status-chip">{alumniStatus[status]}</span>{item.reason && <p>{item.reason}</p>}{['pending', 'confirmed'].includes(status) && Date.parse(slot.endAt) > Date.now() && <button className="v2-button v2-button-secondary" onClick={() => act(s => cancelAlumniBooking(s, actor, item.id, reason), '预约记录已更新。')}>{status === 'pending' ? '撤回申请' : '取消预约'}</button>}</article> })}{!data.bookings.some(item => item.student === actor.id) && <Empty icon={GraduationCap} title="还没有交流申请" description="找到合适的校友后，可以申请开放的时段。"/>}</section></>}
    {view === 'manage' && <><AlumniCertification/>{mine?.status === 'approved' && <><section className="v2-panel v2-list-panel"><SectionHeading title="我的校友资料"/><form className="v2-form" onSubmit={saveProfile}><label>城市<input name="city" defaultValue={mine.city} maxLength={40} required/></label><label>方向<select name="direction" defaultValue={mine.direction}><option>升学</option><option>就业</option></select></label><label>当前经历<input name="experience" defaultValue={mine.experience} maxLength={120} required/></label><label>可交流话题<input name="topics" defaultValue={mine.topics} maxLength={120} required/></label><label>个人介绍<textarea name="bio" defaultValue={mine.bio} maxLength={500}/></label><label><input type="checkbox" name="accepting" defaultChecked={mine.accepting}/> 接受新的交流申请</label><button className="v2-button v2-button-primary">保存校友资料</button></form></section><section className="v2-panel v2-list-panel"><SectionHeading title="我的交流时段"/><form className="v2-form" onSubmit={addSlot}><label>开始时间<input type="datetime-local" name="start" required/></label><label>结束时间<input type="datetime-local" name="end" required/></label><label>地点或交流方式<input name="location" maxLength={120} required/></label><button className="v2-button v2-button-primary">开放时段</button></form>{data.slots.filter(s => s.alumniId === mine.id).map(slot => <div className="v2-alumni-booking" key={slot.id}><p>{alumniTime(slot.startAt)} — {alumniTime(slot.endAt)}</p><p>{slot.location} · {slot.open ? '开放' : '已关闭'}</p>{slot.open && <button className="v2-button v2-button-secondary" onClick={() => act(s => closeAlumniSlot(s, actor, slot.id))}>关闭时段</button>}</div>)}</section><AlumniIncoming/></>}</>}
  </div>
}

import { AlumniAppointmentArea, AlumniCertification, AlumniIncoming } from './alumniWorkflow'
